### ISSUE TITLE
[BUG] Token Action HUD and Auto Stealth not working

### ISSUE THREAD

**Issue by Avitale34** [p4535992/conditional-visibility#11]
**Module Version:** v4.2.23

**Describe the bug**
When using the auto stealth option it only works if stealth is rolled from the sheet, if rolled from Token HUD it does not add condition.

**Comment by rinnocenti** [comment]
besides, for me, just hiding it only records the passive value, not the rolled value.
![image](https://user-images.githubusercontent.com/3178127/158082512-ba6a5aaa-af3f-4837-b0ed-8d7ea1b6a7dc.png)

**Comment by p4535992** [comment]
@rinnocenti  a ok that is maybe a error of mine if the roll result is lower than the passive value i will set the passive , did you need the other use case? A checkbox on the form for avoid that can be a solution for you ?

**Comment by rinnocenti** [comment]
Oh! I understand it makes sense. But for me being stealthy is a premeditated action, and it always needs a roll, I believe. if you have an option to not take the passive it would be better.
(even more an action and to hide which is an action choice in dnd5e)

**Comment by ctbritt** [comment]
What I'm seeing is that a stealth roll of, say 15, is still hiding from other tokens that have a passive perception over 15. They're hidden for everyone.

**Comment by Avitale34** [comment]
Same for me^

**Comment by rinnocenti** [comment]
in new version, senses not work anymore.
![image](https://user-images.githubusercontent.com/3178127/158648486-0b3a619e-81f1-479f-8cd9-f88a9016ed72.png)


(create DF Efects not working too)

**Comment by p4535992** [comment]
try out 0.4.28 and let me know if you see some other issue

**Comment by rinnocenti** [comment]
seems to work.
but I'm trying to edit the AF by DFAE, but when rolled atomatic by stealth the application effect is not that of DF.
How I did edit te hidden effect apply in auto-stealth?

https://drive.google.com/file/d/1QwfONT9iFJY2BDnRWZmXFpoQUwr8FsG9/view?usp=sharing

**Comment by p4535992** [comment]
Solved with 0.4.29, ty for the feedback

**Comment by rinnocenti** [comment]
now he is taking the DF but not applying the stealth roll
the duration part of the effect is also not applied

**Comment by p4535992** [comment]
Sorry i was tired and not notice that, should be fix (hope for the last time) with 0.4.32

**Comment by rinnocenti** [comment]
error
![image](https://user-images.githubusercontent.com/3178127/158945163-371b8360-a0c7-4797-b975-3ed9b2bed1ba.png)

**Comment by p4535992** [comment]
what browser are you using ?

**Comment by rinnocenti** [comment]
I test in the APP.
but I normly use in Chrome.

**Comment by p4535992** [comment]
on chrome it should work, but i will fix it

**Comment by p4535992** [comment]
now should work on app either, let me know
