### ISSUE TITLE
[BUG] Not working in PF2

### ISSUE THREAD

**Issue by jocolamarco** [p4535992/conditional-visibility#13]
**Module Version:** v0.4.24

**Describe the bug**
Immediately throws error messages:

![image](https://user-images.githubusercontent.com/45291719/158418259-696cc0b4-0e85-419e-825f-3d5a589d6808.png)

**To Reproduce**
1. Activate only the Conditional Visibility module and its dependencies
2. Save settings and refresh world
3. See error:
![image](https://user-images.githubusercontent.com/45291719/158418259-696cc0b4-0e85-419e-825f-3d5a589d6808.png)

**Expected behavior**
No errors and working as described.

**Screenshots**
n/a

**Browser:**
 - Chrome

**Foundry Version:** 
9.255

**Game System:** 
PF2e 3.7.2

**Additional context**
![image](https://user-images.githubusercontent.com/45291719/158418626-c7f40f0a-acbd-485d-b622-e06fd7481589.png)

**Comment by p4535992** [comment]
solved this specific issue, but it's seem PF2e has some issue i need time to analyze, Sorry i guess i need more time for make this work onPF2e.
