### ISSUE TITLE
Still not respecting passive perception on observer tokens[BUG]

### ISSUE THREAD

**Issue by ctbritt** [p4535992/conditional-visibility#14]
**Module Version:** v0.4.28

**Describe the bug**
the show/hide function seems just broken. If I have a token (the Hider) and I roll a stealth roll (16), then my Observing tokens (Observers) should or should not be able to see Hider based on their passive perception score, which is fixed in DnD5e. Let's say I have three Observers (1,2,3) Observer1 has 20 passive perception, Observer2 has 16, and Observer3 has 12.  Obsv1 and 2 should be able to see Hider's token, while Obsv3 should not. 

 But at present, on the DM's screen, no matter what Hider rolls, no one can see the token, even if it's a low roll. On the player's screen, everyone can see Hider regardless of his roll. 

To make matters worse, if Obsv 3 makes a perception roll, the Hidden (CV) condition via Dfred's gets applied to _her_ token! 

The topic of invisibility is also rather garbled. If I apply the Invisibility (CV) condition to a Hider2, and then adjust the senses on Obsv1,2,3 to See Invisible > 120, then Hider2 is ... still invisible on both the player's and DM's screens. 

True Sight is equally unable to see the invisible Hider token. 

Here are some settings. 

These are the settings from Hider1, **who just rolled a 16 stealth check**:
<img width="339" alt="Screen Shot 2022-03-16 at 10 34 07 PM" src="https://user-images.githubusercontent.com/4516034/158725865-42a6aa9a-c0ca-4db7-b6d6-67a8d7b9ae21.png">

Here is Hider2, who is **invisible**:
<img width="364" alt="Screen Shot 2022-03-16 at 10 39 38 PM" src="https://user-images.githubusercontent.com/4516034/158725905-1c9791c9-7787-494e-87f3-baa229599400.png">

Here is my Observer, who has a passive perception of 24, so she should be able to see Hider1 (stealth roll of 16). She also has a lantern of revealing, which shows invisible beings within 30 feet of her:
<img width="513" alt="Screen Shot 2022-03-16 at 10 39 53 PM" src="https://user-images.githubusercontent.com/4516034/158726294-8f25aee4-ab90-49f7-bd7a-8af49f8ce358.png">

The old version of the module worked reasonably well. It didn't really allow for things like True Sight or Devil's sight, or a range of vision such as you'd see in a lantern of revealing (30-foot radius to see invisible stuff) but it at least handled auto stealth rolls and whether a token was visible based on the Observer's passive perception. 

I hate to complain since this is a free module and the developer is doing great work to keep it going, but at the moment, the functionality seems just broken, the documentation is a bit confusing, and it just doesn't work as expected. 

**Browser:**
Chrome Version 99.0.4844.51 (Official Build) (arm64)

**Foundry Version:** 
v9.255
**Game System:** 
DnD5e 1.5.7

**Comment by p4535992** [comment]
I tried to fix the problem in version 0.4.29, if you still see some problems enable the setitngs debug module and pass me the logs. I tried to update the documentation https://github.com/p4535992/conditional-visibility/blob/master/wiki/tutorial.md, try to tell me if it comes back to you (for the documentation you could also help in enriching it if it doesn't seem clear enough)

**Comment by Avitale34** [comment]
![image](https://user-images.githubusercontent.com/65961637/158913245-7280a59b-a2af-467e-8336-a13ad35f0da4.png)
Having a similar issue a creature with passive perception of 11 is seeing something hidden with 21 stealth.

**Comment by p4535992** [comment]
@Avitale34 Enable the debug module setting and show me what logs are you seeing, it's seem to work fine on my test. With the latest version 0.4.32 i mean.

**Comment by p4535992** [comment]
Should be solved with the new 0.5.x series.
