### ISSUE TITLE
[BUG] Tokens can be seen in exploration area despite having no vision

### ISSUE THREAD

**Issue by Zolmy** [p4535992/conditional-visibility#15]
**Module Version:** v0.4.28

**Describe the bug**
Actors can be tracked in areas with no vision when fog exploration is on.

**To Reproduce**
1. Move actor to reveal area of the map
2. Move actor back to lose vision of the area leaving exploration vision
3. Move different actor through the revealed area but outside of vision

**Expected behavior**
Actors not in vision cannot be seen / tracked

**Screenshots**
![Screenshot 2022-03-16 203323](https://user-images.githubusercontent.com/101760315/158713815-378f5bac-0911-4f43-a8d2-3d08c7663269.png)
![Screenshot 2022-03-16 203327](https://user-images.githubusercontent.com/101760315/158713558-7c62f394-1c39-406d-9022-f61d477f5876.png)

**Browser:**
 - Chrome

**Foundry Version:** 9.255

**Game System:** DnD5e 1.5.7

**Additional context**
Not sure if this is actually intended functionality or I'm doing something wrong. No other modules aside from conditional visibility and its dependencies are active. In the screenshots above, the bottom green line is the vision range of the player character while the top green line is the edge of the exploration done by moving the character up and then down. The other token in blue can be seen as it moves in the area between the lines.

**Comment by p4535992** [comment]
So no active effect are present on source and target ? Is the module settings "Auto check with passive perception" been checked ?

**Comment by Zolmy** [comment]
I tested it with brand new actors with no active effects on them. Also tried with the passive perception setting both on and off and received the same result. Interestingly enough, the problem only happens from a player perspective.

GM View:
![gm](https://user-images.githubusercontent.com/101760315/158914312-3986c156-7fae-48d0-9606-16d1665d2835.png)

Player View:
![player](https://user-images.githubusercontent.com/101760315/158914328-6bffe564-9748-4568-b750-9073963e0e8f.png)

**Comment by GhostofXavier** [comment]
I can confirm this as well, except there's no difference between player and GM view for me. Also, I have a boatload of modules installed, so feel free to disregard this data point.
![GM view](https://user-images.githubusercontent.com/70046267/158938259-afb72ea0-6678-4b33-9171-de524d339db1.jpg)
![player view](https://user-images.githubusercontent.com/70046267/158938260-154f03a6-584a-45d8-a872-4e553a16abb2.png)

**Comment by GhostofXavier** [comment]
Additional problem found: the players can see GM hidden tokens (Toggle Visibility State) regardless of blocking walls.

I'll fire up an un-modded world and see if it still happens there as well.

*Edit: new world with only Conditional Visibility (current v4.32) and DFred's Convenient Effects (plus their associated dependencies) has this issue.

Players can see every token on the entire map regardless of walls/vision and if its GM hidden.

![Player view 2](https://user-images.githubusercontent.com/70046267/158940205-8768f4e0-9e34-43f3-954f-e7718604d339.png)
.

**Comment by p4535992** [comment]
Should be solved with 0.5.34
