### ISSUE TITLE
[BUG] Giving up and reverting to previous version

### ISSUE THREAD

**Issue by ctbritt** [p4535992/conditional-visibility#16]
I'm sorry to say that the level of complexity introduced into this version is just too much for me. The module doesn't work in a consistent or reliable manner, and while it seems to have some promise, I'm reverting to [szefo09](https://github.com/szefo09) until the bugs can be worked out. I'm happy to help with updating the documentation once this module is in a more workable form. 

Again, I'm really grateful you've picked this up, but I think it's gotten much too complicated to make it really workable at the moment.

**Comment by p4535992** [comment]
Wow and did you need to open a issue for say this ? Have you at least tried to enable the debug module setting like i ask to you for help me out ? Ty for not helping then.

**Comment by ctbritt** [comment]
You're right, and I apologize. I should not have opened an issue on this. I had a tough day yesterday, completely unrelated to your work. 

I have downloaded the code and am looking at the documentation right now. I will try to upload some suggested changes to the readme if you're open to that.

**Comment by p4535992** [comment]
No i'm sorry , i was angry for another thing, is just a game... forgive me

**Comment by p4535992** [comment]
I think i found the error if you wanna wait until tomorrow i will do some tests tonight

**Comment by ctbritt** [comment]
awsome! i'll check out the new version and see if I can't help with feedback.
