### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Gurrgel** [p4535992/conditional-visibility#17]
**Module Version:** v0.4.32

**Describe the bug**
I'm unable to see creatures in Darkness, even with the appropriate senses.

**To Reproduce**
Turned off all my modules except the ones needed for Conditional Visibility, added a token to a map with Token Vision and gave it the "In Darkness" condition. Had another token nearby and gave it the Devil's Sight and/or Truesight senses, and they're still unable to see the target in darkness. I get similar results if giving a token the Invisible condition and giving another token the See Invisible sense. 

**Expected behavior**
I'm quite new to Conditional Visibility so I've not actually used it before, maybe I'm just doing things completely wrong but from my understanding of things a token with the senses mentioned above should be able to see a token with the aforementioned conditions?

**Screenshots**
![image](https://user-images.githubusercontent.com/99760890/158994436-d168cdc9-64e3-4a08-81be-8d65c9354c04.png)
![image](https://user-images.githubusercontent.com/99760890/158994488-f7afb5f3-d2aa-4cc8-bd58-4c9dbd970c80.png)

**Browser:**
Running it in the Foundry application as a DM on my own computer.

**Foundry Version:** 
9.255

**Game System:** 
DnD 5e version 1.5.7

**Additional context**
May be unrelated, but after the previous update to the module I no longer see the various Conditional Visibility senses under the token tab for Vision, and as such I'm unable to set a vision range for the various visions. I would presume that I should still be able to see the token when standing on top of it (which I don't), but I could be wrong?

**Comment by p4535992** [comment]
Made a bunch of fixes from 0.4.32, try out 0.5.2.

_I'm quite new to Conditional Visibility so I've not actually used it before, maybe I'm just doing things completely wrong but from my understanding of things a token with the senses mentioned above should be able to see a token with the aforementioned conditions?_

Here you find the tables for the dnd5e system _sense vs condition_: https://github.com/p4535992/conditional-visibility/blob/master/wiki/table_dnd5e.md

 _May be unrelated, but after the previous update to the module I no longer see the various Conditional Visibility senses under the token tab for Vision, and as such I'm unable to set a vision range for the various visions. I would presume that I should still be able to see the token when standing on top of it (which I don't), but I could be wrong?_ 

The token vision panel configuration is a GM thing, maybe you try to see that  with a player ?ù

Let me know if you encountered some issue.

**Comment by Gurrgel** [comment]
Yeah, my issue was solved with one of the recent patches.
