### ISSUE TITLE
[BUG] Invisibility not respected while auto stealth is.

### ISSUE THREAD

**Issue by ctbritt** [p4535992/conditional-visibility#18]
**Module Version:** v0.4.35

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save'.
5) attach the text file on the github issue

**Describe the bug**
Auto stealth is now working correctly, but invisibility still seems to need some work. In the annotated screenshot below, Bandit (Token A) has a passive perception of 14, Zanna (B) has a passive perception of 11, and Scout (C) has a stealth roll of 14. B is also invisible. 

A _can_ see C because its passive perception equals or exceeds C's stealth roll.
B _cannot_ see C because its passive perception is lower than C's stealth roll. All good. 
However, both A and C _can_ see B, even though it's invisible. B's token should not appear to either of A or C. 

I've attached the debug report. 

I then looked at the default Dfred's condition for Invisible. it's set to ATCV.invisible > custom > 0, when it should be 1, I think. I've edited the effect to be 1, and B now properly disappears, so that's a fix in the defaults that might be made. 

However, applying See Invisible > custom > 2 or greater does not make the invisible B visible to the other tokens. 

**Screenshots**
<img width="798" alt="Screen Shot 2022-03-18 at 4 41 16 PM" src="https://user-images.githubusercontent.com/4516034/159082136-4ee4ee65-3bdc-4d98-9f82-a8483d325655.png">

**Browser:**
Chrome 99.0.4844.74
**Foundry Version:** 
v9.255
**Game System:** 
Dnd 1.5.7

[A-B-C.log](https://github.com/p4535992/conditional-visibility/files/8307600/A-B-C.log)

**Comment by p4535992** [comment]
try out 0.4.38

![img1](https://i.imgur.com/Dk6Gxfk.jpg)
![img2](https://i.imgur.com/BIbWJtV.jpg)
![img3](https://i.imgur.com/C7DDDBE.jpg)
![img4](https://raw.githubusercontent.com/p4535992/conditional-visibility/master/wiki/examples_1/example2.gif)

if something still don't work, i need you to export these actor, maybe threre is some flag or module incompatbiliy i'm missing.
Remember i made this table https://github.com/p4535992/conditional-visibility/blob/master/wiki/table_dnd5e.md for check what _'sense' can see that 'condition'_ tell me if i made something wrong.
By default the hidden state value override the stealth passive from the actor 5e , so for the bandit with 19 of stealth passive the module will use instead the 14 hidden value for the check with the passive perception, tell me if you need some setting for manage this behaviour.

**Comment by ctbritt** [comment]
I think you might be complicating things a bit with the passive stealth, but that might just be a play style. When I play, I only allow stealth when the players say they're trying to be sneaky. Then we roll stealth and if it's lower than, say, a guard's passive perception, the guard spots them. The guard is not actively looking for them. The players never get the benefit of stealth as a passive feature. So I think you could probably drop that entire aspect the module (passive stealth) if that's causing problems?

**Comment by ctbritt** [comment]
So far, everything is looking good, once I updated the DFred’s effects.

**Comment by p4535992** [comment]
> 

yes i think i rewrite some stuff, for make the checker more simple
