### ISSUE TITLE
Nullpointer trying to set effect without DfReds Convenient Effects

### ISSUE THREAD

**Issue by lucasmiranda2711** [p4535992/conditional-visibility#19]
https://github.com/p4535992/conditional-visibility/blob/b5cce040ff11e35cb7e68137bef35f65311578f6/src/module/api.ts#L795

When using another DfReds (Droppables, Pocket change) but not the Convenient Effects, the variable game.dfreds will exist but will be an empty object, thus resulting on nullpointer exception on line 801 while trying to find the effect.

**Comment by p4535992** [comment]
Ty for this, i will fix on the next release

**Comment by p4535992** [comment]
Should solved with 0.5.5
