### ISSUE TITLE
[BUG] Module Conflict with Automated Animations

### ISSUE THREAD

**Issue by Brimcon** [p4535992/conditional-visibility#21]
**Module Version:**
Conditional Visibilty: v0.5.6
Automated Animations version 2.5.6

**Describe the bug**
With Automated Animations enabled Conditional Visibility prints an error and becomes non-functional.
```js
module.js:44 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'API')
[Detected 1 package: conditional-visibility]
    at setupHooks (module.js:44:34)
    at conditional-visibility.js:41:5
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5528:11)
    at Game._initializeGameView (foundry.js:6510:16)
    at Game._initializeView (foundry.js:6486:21)
    at Game.initialize (foundry.js:5433:16)
```

**To Reproduce**
Enable both Conditional Visibility and Automated Animations alongside their dependancies
Refresh page. Observe Console Error.

**Expected behavior**
No Console Error and functional Conditional Visibility.

**Browser:**
Chrome

**Foundry Version:** 
Version 9.255

**Game System:** 
DnD5e 1.5.7

**Additional context**
[CVTest-1648142888547.log](https://github.com/p4535992/conditional-visibility/files/8344030/CVTest-1648142888547.log)

**Comment by p4535992** [comment]
Can't replicate this issue, but other peolple show the same error in different use case, try out 0.5.7 and  tell me if the error still show up.

**Comment by Brimcon** [comment]
Still occurs on my end. I am also running on a dedicated remote server, Lemme see if it happens on local server.

**Comment by Brimcon** [comment]
Confirmed it happens on my local server.
I have an actor on a fresh scene (Human Fighter from Starter Heroes in DnD5e)
After having that actor on the field and hitting refresh prints the error. 
![image](https://user-images.githubusercontent.com/7198283/160215265-70036910-cf9e-4ce7-ae43-80015f0d4509.png)

With the actor removed from the scene the error does not occur on Local, still occurs on Remote.

**Comment by Brimcon** [comment]
Update on Local server: Refreshing multiple times occasionally brings up the error. Its 100% Consistant on remote, but occurs every 6 or 7 refreshes on Local/Electron

**Comment by Brimcon** [comment]
Fixed!
