### ISSUE TITLE
[BUG] Combat Utility Belt integration

### ISSUE THREAD

**Issue by DmTheTulio** [p4535992/conditional-visibility#22]
![image](https://user-images.githubusercontent.com/102385137/160186388-d35eae89-a414-459f-a6b4-9f4c63a5a0ed.png)
[dmthetulio-tomb-of-annihilation-friday.forge-vtt.txt](https://github.com/p4535992/conditional-visibility/files/8353289/dmthetulio-tomb-of-annihilation-friday.forge-vtt.txt)

I can't get the module to work, I did the steps throughout the readme but still, the hidden condition doesn't seem to work, nor does it work automatically

**Comment by p4535992** [comment]
DCE and CUB are not synchronized, you have to set them by hand.

You have to set the active effect as described in the documentation (yes I know it's a bit boring to read), but once you get your hands on it you realize that it is highly customizable. I am attaching a quick video that I hope will help you.

![cub](https://github.com/p4535992/conditional-visibility/blob/master/wiki/video/feature_cub_cv_1.gif?raw=true)

The active effect changes you need are :
`ATCV.hidden=1`: mandatory this is if you the `hidden` effect, but you can customize with any id you want, a suffix `(CV)` is advisable.
`ATCV.conditionType=condition`: otional but suggested.

**Comment by DmTheTulio** [comment]
Okay, I added what you written by copying them from CE - which helps a lot, since now I can use CE a bit better. But I am still at loss with the hidden effect - it doesn't apply automatically when rolling stealth, and it doesn't really seem to be working at all, as opposed to invisible - which works just as expected

**Comment by DmTheTulio** [comment]
Also I noticed that the module "less fog" breaks the dm view of tokens (I still see an invisible token as other tokens, but my players don't) might be worth noting

**Comment by p4535992** [comment]
What did you mean  _it doesn't apply automatically  when rolling stealth?_  Seem to work to me, if you click stealth on the character sheet no hidden effect is applied ? 
The 'auto stealth' is a token only feature, so if you roll from a 'actor' on the sidebar is not applied .

**Comment by DmTheTulio** [comment]
I roll stealth while having the token selected from the token action hud - and it doesn't work, tried from the sheet as well - same thing

**Comment by DmTheTulio** [comment]
Also: this shows up when I attack while having the hidden condition on a token:
custom-roll.js:272 BetterRolls | Card loaded existing item data Fist
utils.js:1565 Uncaught (in promise) TypeError: CV?.unHide is not a function
[Detected 1 package: midi-qol]
    at removeTokenCondition (utils.js:1565:7)
    at BetterRollsWorkflow.removeHiddenInvis (utils.js:1548:8)
    at BetterRollsWorkflow._next (workflow.js:2793:34)
    at BetterRollsWorkflow.next (workflow.js:259:21)
    at BetterRollsWorkflow._next (workflow.js:2789:17)
    at async BetterRollsWorkflow.next (workflow.js:259:10)
    at async BetterRollsWorkflow._next (workflow.js:2884:12)
    at async BetterRollsWorkflow.next (workflow.js:259:10)
    at async BetterRollsWorkflow._next (workflow.js:2884:12)
    at async BetterRollsWorkflow.next (workflow.js:259:10)
    at async BetterRollsWorkflow._next (workflow.js:2884:12)
    at async BetterRollsWorkflow.next (workflow.js:259:10)
    at async BetterRollsWorkflow._next (workflow.js:2884:12)
    at async BetterRollsWorkflow.next (workflow.js:259:10)

**Comment by DmTheTulio** [comment]
Is there maybe an option in midi-qol I need to have in order for the auto-stealth to work?

**Comment by DmTheTulio** [comment]
2 more problems I uncovered from the log:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'API')
[Detected 1 package: conditional-visibility]
    at setupHooks (module.js:44:34)
    at conditional-visibility.js:41:5
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5528:11)
    at Game._initializeGameView (foundry.js:6510:16)
    at Game._initializeView (foundry.js:6486:21)
    at Game.initialize (foundry.js:5433:16)

api.js:432 Uncaught (in promise) TypeError: this.effectInterface.hasEffectAppliedOnToken is not a function
[Detected 1 package: conditional-visibility]
    at Object.hasEffectAppliedOnToken (api.js:432:51)
    at prepareActiveEffectForConditionalVisibility (lib.js:709:23)
    at async Object.updateToken (module.js:220:25)

**Comment by p4535992** [comment]
there is a warning on the hud dialog , you can't roll the stealth from that, tested with character sheet seem to work, any error on the web console ?

The midi error should be solve not sure why is keep to pop up...

The reading API undefined should be solved with the next release

**Comment by DmTheTulio** [comment]
Unfortunately not for me: I tried rolling from LMRFY, monk's bar, sheet and hud - nothing gives me the hidden status on the token

**Comment by DmTheTulio** [comment]
Let me know if I should give you my settings, maybe some other logs, I think that the premise of this module is incredible and I would love to see my rouges dissapearing from the map ;)

**Comment by DmTheTulio** [comment]
Also just read - no, no errors when I roll stealth which is strange

**Comment by Brimcon** [comment]
I think this is related to my issue #21. I get both errors said in this thread. First upon load and second upon rolling stealth on any character with Apply Hidden(CV) upon stealth when CV doesn't hook into the API as expected.

**Comment by p4535992** [comment]
- Midi Qol bug is solved.
- Less Fog bug is solved, detail on the known issues paragraph, _just make sure the module 'Less Fog' settings 'Reveal Tokens' and 'Reveal to All Players' are set to false (uncheked box) both_.
- Auto stealth seem to work, maybe there is a module incompatibility i miss.
- Probably fixed https://github.com/p4535992/conditional-visibility/issues/21, but let me know

**Comment by DmTheTulio** [comment]
![image](https://user-images.githubusercontent.com/102385137/160246016-fb1b92d4-4b22-4449-a48b-81b5475b704c.png)
[dmthetulio-tomb-of-annihilation-friday.forge-vtt2.txt](https://github.com/p4535992/conditional-visibility/files/8355760/dmthetulio-tomb-of-annihilation-friday.forge-vtt2.txt)

New day, new errors - the hidden condition seems to work now, kinda? It actually hides the actor now so that is a win

Less fog sill breaks the module for me - I made sure to uncheck both options as you told me but it doesn't work (actors are not hidden from players - they can still see them, the gm view is still broken) and libwrapper still chokes an error

Auto stealth still doesn't work - i will try disabling some modules later to help with that

**Comment by DmTheTulio** [comment]
Oh and the error was quite something - If I gave an actor any sense - suddenly all the senses started to pop at random

I gave darkvision - and it gave blindsight, devilsight and others, started deleting them etc - lagged so hard I needed to delete the actor

**Comment by DmTheTulio** [comment]
Midi QoL works - hidden or invisible target attacks with advantage, and it removes those conditions after the attack

**Comment by DmTheTulio** [comment]
My bad - it removes the hidden effect, but strange thing happens with invisible - it gets removed and then applied again after the attack. Logs:
[invisiblehidden.txt](https://github.com/p4535992/conditional-visibility/files/8355790/invisiblehidden.txt)

**Comment by Brimcon** [comment]
#21 is indeed fixed! Thanks. But now I'm having issues with Hidden/Invisible not being removed/granting advantage ala MidiQOL. I'll discuss here and close the other issue.

**Comment by p4535992** [comment]
k replicate... i will fix...

**Comment by Brimcon** [comment]
Something else to look into is "Disable for Non-Hostile NPC." not working. Apologies for piling all these bug reports into this one thread.

**Comment by p4535992** [comment]
The loop delete multiple sense bug should be fixed , or at least i think, so many use case...

**Comment by DmTheTulio** [comment]
The senses are fixed - I still can't get auto stealth to work tho - no errors with that nothing. Invisible, Obscured and Darkness work fine

**Comment by DmTheTulio** [comment]
Okay I got it - better rolls for 5e caused the auto-stealth to fail - we can close the topic

**Comment by p4535992** [comment]
ty god i was going nuts for that, i'll try to made a fix for that... 
little by little the module seems to me to become more and more stable ... fingers crossed.
also Tim told me that he will integrate CV into DAE (hooray) and update the old pre 0.4.X integration on midi-qol

**Comment by p4535992** [comment]
Should be work with better roll either
