### ISSUE TITLE
[BUG] Player lacks permission to update Token

### ISSUE THREAD

**Issue by Berytak** [p4535992/conditional-visibility#27]
**Module Version:** v0.5.25

**Describe the bug**
Every player gets the error "Player lacks permission to update Token" for every Token except player tokens.

**To Reproduce**
Activating the module starts the error message flooding on the player backend. I, as the DM, have no error in my logs/debugging window.

**Expected behavior**
No error message ;-)

**Screenshots**
![image](https://user-images.githubusercontent.com/85394657/161208759-3ceaab04-57e7-4873-893f-bdae885bfe6e.png)

**Browser:**
Any 

**Foundry Version:** 
Version 9 Build 255

**Game System:** 
D&D5e

**Additional context**
client side log
[Error Log.log](https://github.com/p4535992/conditional-visibility/files/8395304/Error.Log.log)

**Comment by p4535992** [comment]
@Berytak  I'm so stupid, sorry for the inconvenience, if god wants I solved it with 0.5.26, but I keep making mistakes a lot. Let me know it.

**Comment by Berytak** [comment]
Not a problem at all, it was just a bit tricky to find the scapegoat that throws the error. If I can provide any help with test or other logs, I'm glad to help.

**Comment by p4535992** [comment]
This should be finally solved. Feel free to reopen the issue if you keep rediscovering it
