### ISSUE TITLE
[BUG] significant latency

### ISSUE THREAD

**Issue by ref2335** [p4535992/conditional-visibility#28]
0.5.30 have discovered significant introduced latency when moving tokens.  All doors and stairs icons(stairwells module) are invisible to players.

**Comment by p4535992** [comment]
try out 0.5.32, cannot replicate the super latency, but i solved some issue with door and stairs, maybe things were connected.

**Comment by ref2335** [comment]
I see the issue with doors and stairs is resolved with .5.32, however the latency is very pronounced.  Feel free to message me on Discord if you'd like to gain access to my world to troubleshoot or document the issue.

Discord: Ref Lansky#3878

**Comment by p4535992** [comment]
@ref2335 I did a lot of bug fixing, can you let me know if the problem persists? if the answer is yes I ask you to pass me the scene or the world that is giving you this problem. You can contact me on discord if you want (Discord: 4535992#1766)

**Comment by ref2335** [comment]
Latest release seems to not have the latency issues any longer. I will continue to monitor, but things are looking much better!!

**Comment by p4535992** [comment]
Good to know. Ty.
