### ISSUE TITLE
[BUG] Duplicate token configuration panel and some sight issue

### ISSUE THREAD

**Issue by rinnocenti** [p4535992/conditional-visibility#29]
**Module Version:** v0.5.35

everything was different and nothing is working correctly

not applying the hide effect.
When someone rolls stealth the numbers are not being registered, the effect is not placed, and the superiority of value is not working properly.

in the video for example the hero is not hidden even so he is not shown to the bad guys.
trying to put the condition through the HUD shortcut it is not applied in the effects, however it is hidden and there is no way to remove this hidden from the token anymore.
if you play a stealth from the bandit, it doesn't go into auto hide (even if it's configured for that), the value is captured by the HUD shortcut but it's not captured in the token's config.

even with low stealth it is still hidden from those with a higher passive perception than the number rolled.

It's not in the video but it happens that with an unlinked NPC it's that if he uses stealth, all the other tokens are out of his sight, instead of the other tokens having him "invisible" in the vision of the stealth player, it's the others who stay "invisible"

https://user-images.githubusercontent.com/3178127/162071596-39986da7-6cb3-4882-afd6-b19a89733299.mp4

**Comment by rinnocenti** [comment]
I updated the module to version .56
and it has now lost compatibility with the Levels module.
turning the screen gray and making it impossible for players to see anything. (moving the player by the GM doesn't work either).

even with the modules disabled some things are not working as expected (I think)

1) all my token prototypes default to "Use stealth passive" already enabled. without knowing it activating the auto stealth roll causes unexpected effects, such as other tokens disappearing (since it defaults to hiding with passive, as if all tokens are always hiding). the expected behavior is that if this roll is chosen for automatic stealth, the passive will no longer be active. or at least one macro to disable/enable all these options for all token prototypes.

![image](https://user-images.githubusercontent.com/3178127/162105791-892b03f5-b508-4bee-8e3b-dd469d0f3b90.png)

2) In addition, old tokens that used the module still have the old flags and it is not possible to remove the previous values, even applying new ones it starts to vary. if it is in characters linked with the character sheet these values are permanent and without editing the fags by hand they do not come out. 

again a macro to clear the data would be nice because if it doesn't start giving weird results (like not recording the rolled values)

3) Apparently when the stealth roll is below the passive perception of any token from the opposing party (hostiles/friends) the engraved stealth value is always 1.
I don't know if this is the intended behavior, if it is I liked it, because in previous versions it didn't do that, the value was kept even low and each player saw tokens that their perception allowed. so I don't know what the intended behavior is here, and some users might be confused.

4)player characters are behaving strangely, the active self hide effect is not activated when players roll.
however the value is recorded in the flags and the effect of being without visualization works. however there is no way to change this condition as the token's HUD menu does not display the hide value, and changing it causes different behavior between GM and Player, as the effect condition was not applied, there is no way to change/check the value without being rerolled or hard edited the flag. (on linked tokens the effect is applied normally as expected)

![image](https://user-images.githubusercontent.com/3178127/162108294-da1fd65d-5312-4a66-b1f0-ff51f245e815.png)
Vision of token player

![image](https://user-images.githubusercontent.com/3178127/162108373-4fdc6355-e495-454a-9f2c-08943280c860.png)
Vision of bandit token

**correct unlinked token behavior**
![image](https://user-images.githubusercontent.com/3178127/162108814-fe7cdc1e-e0b4-4a69-96e1-1a96477e1fb5.png)
hidden Bandit vision 
![image](https://user-images.githubusercontent.com/3178127/162108863-e1d151ff-ca71-4cde-8a30-efe3fbff5df2.png)
Player vision


however if I remove the bandit effect, it remains hidden for the player.
although the token's hud appears to be zero, the flag keeps its value.

**Comment by p4535992** [comment]
Sorry for the trouble @rinnocenti , and ty very much for this detailed issue, from my tests it'seem all is manageable  with the new AE effect 'Stealthed' on version 0.5.38, let me know if you still encounter some problem.

**Comment by lucaspicerni** [comment]
Hi! I'm having similar issues, but not being able to find patterns in errors or even reproduce them. Sometimes they happen, sometimes they don't, and only with certain actors. In the token vision configuration, sometimes 3 or 4 repetitions of the Senses and Conditions menu appear. Usually after performing an attack, specific actors disappear.

![image](https://user-images.githubusercontent.com/95550238/164067535-ef7b8011-afa4-4e09-b100-d697594a5f2a.png)
