### ISSUE TITLE
I think you've got it! 

### ISSUE THREAD

**Issue by ctbritt** [p4535992/conditional-visibility#31]
Latest version seems to fix all the issues I was having. The included macros remove the flags, and people can see only what they're supposed to see. Well done! Now we just wait for Levels or Perfect Vision to break everything again! :) 

Seriously, though, congratulations. It's probably been a bit frustrating at times, but the effort seems to have paid off.

**Comment by p4535992** [comment]
IoI ty for the support, sadly i'll already see some bug on my side so i'll probably rewrite something this week end.
P.S. i close the issue .
