### ISSUE TITLE
[BUG] Stealth values ​​are not taken when checking it.

### ISSUE THREAD

**Issue by salamander-git** [p4535992/conditional-visibility#33]
There is no way to get the Hidden status to be applied automatically (using the rolled value) when checking the Stealth.
If you independently enter the value of the stealth check into a temporary effect, then when the system works. But I would like to automate it.

Foundry - V9
DnD5e - 1.5.7
Modules available: TAH, MTB, DAE, DFreds Convenient Effects, Perfect Vision
**Module Version:** v0.5.39

**Comment by p4535992** [comment]
should be solved with 0.6.0 (i hope...)
