### ISSUE TITLE
[BUG] Unexpected behavior: Vision types reveal hidden enemies.

### ISSUE THREAD

**Issue by Orbdamu** [p4535992/conditional-visibility#37]
Different vision types, such as devil sight, darkvision and truesight reveal hidden targets. From my understanding, this should only be the case, as it should only be dependent on perception.

debugging log:

DEBUG | conditional-visibility | [darkvision][hidden](9.4) Is true, 'Tindrig Svindleholm' can see 'Pod Demon' 
DEBUG | conditional-visibility | [darkvision](12.3) Is true, 'Tindrig Svindleholm' can see 'Pod Demon' 
DEBUG | conditional-visibility | FINAL => 'Tindrig Svindleholm' can see 'Pod Demon' 
 

Foundry - V9
DnD5e - 1.5.7
Modules available: TAH, MTB, DAE, DFreds Convenient Effects
Module Version: v0.5.39

**Comment by p4535992** [comment]
Should be solved with the 0.6.X series the new 'stealth' Active effect for dnd5e can be seen only from the 'perception'.
Let me know if something not work like you expected.
