### ISSUE TITLE
[BUG] Conditional Visibility spam upon Refresh

### ISSUE THREAD

**Issue by Brimcon** [p4535992/conditional-visibility#38]
**Module Version:** v0.6.1
**Foundry Version:** 9.269
**D&D Version:** 1.6.1

**Describe the bug**
Upon world refresh, ALL Stealth rolls in the log are checked and pop up with a window asking what to do, even month old checks.

If Auto is enabled, it auto applies all Active Effects upon refresh.
**To Reproduce**
1. Have Conditional Visibility enabled
2. Roll a bunch of Stealth Checks. Optional: Have multiple actors roll checks.
3. Have `Auto apply effect for pre configured skills` Enabled
4. Refresh Browser.
5. Watch window spam
6. If Skip Dialogue Confirmation is enabled, watch Active Effects on all actors.

**Expected behavior**
Maybe I'm misinterpreting the idea now but shouldn't this only occur on new checks?

**Screenshots**
![image](https://user-images.githubusercontent.com/7198283/170881518-c87a6411-b7e9-4f3d-9608-1f0dbb0c75ea.png)
![image](https://user-images.githubusercontent.com/7198283/170881552-39d50c87-cd19-4697-b3cd-b735b34f04c5.png)

**Browser:**
 Chrome

**Additional context**
In my active play world this gets spammed six times
```js
module.js:1066 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
[Detected 1 package: conditional-visibility]
    at Object.renderChatMessage (module.js:1066:32)
    at module.js:115:16
    at Hooks._call (foundry.js:294:14)
    at Hooks.call (foundry.js:279:33)
    at ChatMessage.getHTML (foundry.js:15308:11)
    at async ChatLog._renderBatch (foundry.js:57754:21)
    at async ChatLog._renderInner (foundry.js:57723:5)
    at async ChatLog._render (foundry.js:3068:19)
    at async ChatLog._render (foundry.js:47136:5)
    at async ChatLog._render (foundry.js:57714:5)
```

**Comment by p4535992** [comment]
@Brimcon

_Maybe I'm misinterpreting the idea now but shouldn't this only occur on new checks?_

yes , everyting should be loaded after the game is ready, so only with new checks.

I have added some checks.

Try out version 0.6.3, and let me know if the issue persist.

**Comment by Brimcon** [comment]
It still occurs on 0.6.3, This is after resetting the module as well.
Interestingly, after I CTRL+F5, it doesn't do it, but upon the next F5 the propmts return.

**Comment by p4535992** [comment]
Can I ask you to pass me the world? or just the chat.db file because i parse the chat for the autoskills feature.
Unfortunately I can't find a pattern on my side.
My discord account is 4535992#1766

**Comment by p4535992** [comment]
Try out 0.6.4 and let me know it

**Comment by Brimcon** [comment]
Still occurs upon refresh.
![image](https://user-images.githubusercontent.com/7198283/171046812-9345c441-479e-4b69-92fe-31de67058da3.png)

**Comment by p4535992** [comment]
Try out 0.6.6

**Comment by Brimcon** [comment]
It works! Thank you!
