### ISSUE TITLE
[BUG] Auto Roll not apply DF Convenient effect edit

### ISSUE THREAD

**Issue by rinnocenti** [p4535992/conditional-visibility#42]
**Module Version:** v0.6.6

**Describe the bug**
rolling Auto stealth, does it apply a new stealth or hide effect, when you would expect to use the condition set in DF Convenient effects?
it applies a clean condition, without the changes made to the DF CE condition, making it impossible to set duration or other effects like advantages when it is hidden etc..

**To Reproduce**
1. Edit the hidden (CV) condition in DF convenient effects
2. Roll stealth in auto mode.
3. check the apply effect.
4. the applied effect is not the DF convenient effect

**Expected behavior**
that changes made to the effect are applied to the auto roll

**Screenshots**

**Browser:**
 - App

**Foundry Version:**  9.269

**Game System:** DnD5e 1.6.2

**Additional context**
happens with or without other modules installed.

**Comment by p4535992** [comment]
@rinnocenti  Try out 0.6.9

**Comment by rinnocenti** [comment]
Work well now

**Comment by rinnocenti** [comment]
not so good.
Data coming from the DAE is not transferred. such as Special Durations for example.

other data (Effects default) apparently transfers correctly

**Comment by p4535992** [comment]
Can you export the effect in exams ?

**Comment by p4535992** [comment]
There is  a strange issue with DAE, on 0.6.10 i made a bug fix ?
Anyway i open other tickets on dfred module and on DAE module.

**Comment by rinnocenti** [comment]
Works
