### ISSUE TITLE
Divide "Auto apply effect for pre configured skills" into stealth and perception

### ISSUE THREAD

**Issue by Orbdamu** [p4535992/conditional-visibility#43]
I would like to seperately choose whether to apply automatic stealth or automatic perception checks. For my use case, I want only automatic perception, as I have a monk in my high level campaign with 19 passive stealth, meaning even enemies he just attacked and stands right in front of without making an effort of hiding cannot see him, and in such a case an automatic stealth calculation doesn't really make sense.

**Comment by p4535992** [comment]
I added on the token configuration the customization for the auto skill roll, maybe is what you want?
