### ISSUE TITLE
[BUG] module is conflicting with MIDI

### ISSUE THREAD

**Issue by rinnocenti** [p4535992/conditional-visibility#45]
**Module Version:** v0.6.11

**Describe the bug**
bonus from any attribute on damage is reset

**To Reproduce**

1) have the MIDI and CV modules active.
2) The MIDI module with full Automation.
[fvtt-midi-qol-settings.zip](https://github.com/p4535992/conditional-visibility/files/8863870/fvtt-midi-qol-settings.zip)

3) attacks have their damage bonus by attributes reset to zero.

![image](https://user-images.githubusercontent.com/3178127/172682217-98965d24-efa1-4bd2-86d9-80fd6b7def45.png)

**Expected behavior**
as the module should operate only the field of vision it shouldn't interfere with the generation of attack cards in the chat, but it's happening.

**Comment by rinnocenti** [comment]
I changed the MIDI play order (as a priority) and the CV (without priority) in libwrapper and it got it right again.

but I still don't know if it causes other problems.

**Comment by p4535992** [comment]
there seems to be a synchronization problem between the updates of the actor between the two modules, I didn't understand anything, but Tim seems to have found the solution on his side with Midi it should be solved with the next Midi release
