### ISSUE TITLE
Help: D&D 5e elevation

### ISSUE THREAD

**Issue by ravingdragoon** [p4535992/conditional-visibility#46]
Is there a way to get the 5e system to check the elevation? It says in the table that elevation is not checked, and I don't seem to be able to get the elevation difference to be recognized.

**Comment by p4535992** [comment]
Have you setted the active effect change `ATCV.conditionElevation = true` like describe in the documentation ?
Enable the debug module settings and show to me the logs for confirm the check.

**Comment by ravingdragoon** [comment]
So I think the issue is that I just don't understand where/how I am supposed to make that change.

**Comment by p4535992** [comment]
Like in this video
![img](https://github.com/p4535992/conditional-visibility/raw/master/wiki/video/feature_image_1.gif)
 but instead you use :   
`ATCV.conditionElevation = true`

if you use Dfred Convienient Effect you can directly edit the effect on dfred panel.

**Comment by ravingdragoon** [comment]
So it should be like this:

Attribute Key					| Change Mode	| Effect Value
ATCV.conditionElevation	| Custom				| true

?

**Comment by ravingdragoon** [comment]
As a side question, why is 5e not set to automatically check for elevation differences in the calculations?

**Comment by p4535992** [comment]
_So it should be like this:

Attribute Key | Change Mode | Effect Value
ATCV.conditionElevation | Custom | true

?_

yes it should work

_As a side question, why is 5e not set to automatically check for elevation differences in the calculations?_

bad community feedback, the elevation check is useful only for people a little more skilled and in combination with other modules, so is a statistic decision , the majority of people are just happy wihtout a elevation check on the middle.
The module is already integrated with "Levels" so you don't need to set the value to true if you use that module.

**Comment by ravingdragoon** [comment]
Hmm.. I do have levels installed and it is not working. I will do some further troubleshooting and get back to you.

**Comment by ravingdragoon** [comment]
Ugh.. It is the module Token Lean. I have disabled it and things seem to be working properly at the moment.

**Comment by p4535992** [comment]
@ravingdragoon i added a module settings for enable by default the elevation check if you can found helpful.
