### ISSUE TITLE
[BUG] Error message "Cannot redefine property: isVisible"

### ISSUE THREAD

**Issue by SR5060** [p4535992/conditional-visibility#6]
foundry 9.242
dnd5e 1.5.6
conditional visibility 0.3.1

![image](https://user-images.githubusercontent.com/85184490/148781851-6045157b-a1d4-4254-96f3-2f4235ff74e5.png)

**Comment by p4535992** [comment]
patch the error on 0.3.2

**Comment by p4535992** [comment]
This issue is closed, because the new series 0.4.X is just to different, checkout the last version of the module.
